---
- name: System Config | Install PIP
  yum:
    name:
      - python3-devel
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: System Config | Install PIP
  apt:
    name: python3-pip
  when: ansible_os_family == "Debian"

- name: System Config | Install PyMongo from PIP
  pip:
    name: pymongo
    state: "{{ mongodb_pymongo_pip_version is defined | ternary('present', 'latest') }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
    extra_args: --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --upgrade pip
  tags:
    - pymongo
