---
#- name: Enable Firewalld

- name: FirewallD | Install firewalld packages
  apt:
    name: firewalld
    state: present
  when: ansible_os_family == "Debian"

- name: FirewallD | Allow access on port {{ mongodb_conf_port }}
  firewalld:
    port: "{{ mongodb_conf_port }}/tcp"
    permanent: yes
    state: enabled
  notify: firewalld restart
