---

- name: Create MongoDB config directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - path: "{{ mongodb_conf_file | dirname }}"
  notify: mongodb restart


- name: Configure MongoDB service and daemon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: mongod-init.conf.j2
      dest: "{{ mongodb_conf_file }}"
    - src: mongod.service.j2
      dest: "{{ mongodb_daemon_unitfile }}"
  notify:
    - systemd reload
    - mongodb restart


- name: Create Mongo data directory {{ mongodb_conf_dbPath }} 
  file:
    path: "{{ mongodb_conf_db_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod


- name: Create Mongo log directory {{ mongodb_conf_dbPath }} 
  file:
    path: "{{ mongodb_conf_log_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod

- include: selinux.yml
  when: ansible_facts['os_family'] == "RedHat"


- name: Disable Transparent Huge Pages (THP)
  template:
    src: disable-transparent-huge-pages.service.j2
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: "0644"