---

- name: Mongo Config | Check if config directory avaliable
  stat:
    path: "{{ mongodb_conf_file | dirname }}"
  register: stat_conf_directory

- name: Mongo Config | Create config directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  when: stat_conf_directory.stat.exists == false



- name: Mongo Config | Check if database directory {{ mongodb_conf_db_dir }}
  stat:
    path: "{{ mongodb_conf_db_dir | dirname }}"
  register: stat_db_directory
  when: mongodb_conf_db_dir  != "/var/lib/mongo"

- name: Mongo Config | Create database directory {{ mongodb_conf_db_dir }} 
  file:
    path: "{{ mongodb_conf_db_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod
  when: 
    - mongodb_conf_db_dir  != "/var/lib/mongo"
    - stat_db_directory.stat.exists == false


- name: Mongo Config | Check if database directory {{ mongodb_conf_log_dir }}
  stat:
    path: "{{ mongodb_conf_log_dir | dirname }}"
  register: stat_log_directory
  when: mongodb_conf_log_dir  != "/var/log/mongodb"

- name: Mongo Config | Create log directory {{ mongodb_conf_log_dir }} 
  file:
    path: "{{ mongodb_conf_log_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod
  when: 
    - mongodb_conf_log_dir  != "/var/log/mongodb"
    - stat_log_directory.stat.exists == false