---
- name: Mongo Replset | Copy replicaset conf js files
  template:
    src: "{{ item }}.js.j2"
    dest: "/tmp/{{ item }}.js"
    mode: "0755"
  loop:
    - initReplicaset
    - addMembers
  when: "'master' in group_names"

- name: Mongo Replset | Init replicaset on primary {{ inventory_hostname }}
  shell: mongo --host {{ inventory_hostname }} --authenticationDatabase admin --username {{ mongodb_root_account }} --password {{ mongodb_root_password }} /tmp/initReplicaset.js
  register: replicaset_status
  ignore_errors: yes
  failed_when:
    - replicaset_status.rc != 0
  when: "'master' in group_names"

- name: Mongo Replset | Add members on primary {{ inventory_hostname }}
  shell: mongo --host {{ inventory_hostname }} --authenticationDatabase admin --username {{ mongodb_root_account }} --password {{ mongodb_root_password }} /tmp/addMembers.js
  register: replicaset_status
  ignore_errors: yes
  failed_when:
    - replicaset_status.rc != 0
  when: "'master' in group_names"
