---
- name: System Config | Configure MongoDB init-service and daemon
  template:
    src: mongod-init.conf.j2
    dest: "{{ mongodb_conf_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: mongodb restart
