---
- name: SELinux | Disable service
  selinux:
    state: disabled
  register: status_selinux
  when: not configure_selinux | bool

- name: SELinux | Enable service
  selinux:
    state: enforcing
    policy: targeted
  register: status_selinux
  when: configure_selinux | bool

- name: SELinux | Reboot if status changed
  reboot:
    reboot_timeout: 3600
  when: status_selinux.changed

- name: SELinux | Install support packages
  yum:
    name:
      - checkpolicy
      - policycoreutils-python-utils
    state: present
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux | bool
    - ansible_selinux.status == 'enabled'

- name: SELinux | check mongodb_cgroup_memory module enabled already
  shell: "semodule -l | grep mongodb"
  register: status_cgroup_module
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux | bool
    - ansible_selinux.status == 'enabled'

- name: SELinux | mongodb_cgroup_memory | Copy custom policy
  copy:
    src: selinux/mongodb_cgroup_memory.te
    dest: /tmp/mongodb_cgroup_memory.te
    mode: 0400
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - not "mongodb_cgroup_memory" in status_cgroup_module.stdout

- name: SELinux | mongodb_cgroup_memory | Compile custom policy module
  command: checkmodule -M -m -o /tmp/mongodb_cgroup_memory.mod /tmp/mongodb_cgroup_memory.te
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - ansible_selinux.status == 'enabled'
    - not "mongodb_cgroup_memory" in status_cgroup_module.stdout

- name: SELinux | mongodb_cgroup_memory | Build custom policy package
  command: semodule_package -o /tmp/mongodb_cgroup_memory.pp -m /tmp/mongodb_cgroup_memory.mod
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == 'enabled'
    - not "mongodb_cgroup_memory" in status_cgroup_module.stdout

- name: SELinux | mongodb_cgroup_memory | Load custom policy package
  command: semodule -i /tmp/mongodb_cgroup_memory.pp
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - ansible_selinux.status == 'enabled'
    - not "mongodb_cgroup_memory" in status_cgroup_module.stdout

- name: SELinux | Set MongoDB context for {{ mongodb_conf_db_dir }} directory
  sefcontext:
    target: "{{ mongodb_conf_db_dir }}(/.*)?"
    setype: mongod_var_lib_t
    reload: true
    state: present
  when:
    - configure_selinux | bool
    - mongodb_conf_log_dir  != "/var/lib/mongo"
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - ansible_selinux.status == 'enabled'
  notify: mongodb restart

- name: SELinux | Set MongoDB context for {{ mongodb_conf_log_dir }} directory
  sefcontext:
    target: "{{ mongodb_conf_log_dir }}(/.*)?"
    setype: mongod_log_t
    reload: true
    state: present
  when:
    - configure_selinux | bool
    - mongodb_conf_log_dir  != "/var/log/mongodb"
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - ansible_selinux.status == 'enabled'
  notify: mongodb restart

- name: SELinux | Ensure MongoDB file contexts are applied
  shell: restorecon -vr "{{ item }}"
  with_items:
    - "{{ mongodb_conf_db_dir }}"
    - "{{ mongodb_conf_log_dir }}"
  register: restorecon
  changed_when: restorecon.stdout | length > 0
  when:
    - configure_selinux | bool
    - ansible_selinux is defined
    - ansible_selinux  | bool
    - ansible_selinux.status == 'enabled'

- name: SELinux | Configure MongoDB network port {{ mongodb_conf_port }}
  seport:
    ports: "{{ mongodb_conf_port }}"
    proto: tcp
    setype: mongod_port_t
    reload: true
    state: present
  notify: mongodb restart
  when:
    - ansible_selinux | bool
    - ansible_selinux.status == "enabled"
