---
- name: Mongo Config | Check if config directory avaliable
  stat:
    path: "{{ mongodb_conf_file | dirname }}"
  register: stat_conf_directory

- name: Mongo Config | Create config directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  when: not stat_conf_directory.stat.exists

- name: Mongo Config | Check if database directory {{ mongodb_conf_db_dir }}
  stat:
    path: "{{ mongodb_conf_db_dir | dirname }}"
  register: stat_db_directory
  when: mongodb_conf_db_dir  != "/var/lib/mongo"

- name: Mongo Config | Create database directory {{ mongodb_conf_db_dir }}
  file:
    path: "{{ mongodb_conf_db_dir }}"
    state: directory
    recurse: yes
    mode: "0755"
    owner: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
    group: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
  when:
    - mongodb_conf_db_dir  != "/var/lib/mongo"
    - not stat_db_directory.stat.exists

- name: Mongo Config | Check if database directory {{ mongodb_conf_log_dir }}
  stat:
    path: "{{ mongodb_conf_log_dir | dirname }}"
  register: stat_log_directory
  when: mongodb_conf_log_dir  != "/var/log/mongodb"

- name: Mongo Config | Create log directory {{ mongodb_conf_log_dir }}
  file:
    path: "{{ mongodb_conf_log_dir }}"
    state: directory
    recurse: yes
    mode: "0755"
    owner: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
    group: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
  when:
    - mongodb_conf_log_dir  != "/var/log/mongodb"
    - not stat_log_directory.stat.exists
