---
- name: Mongo Replset | Checking For Existing Replication Set Keyfile {{ mongodb_replication_key_file }}
  stat:
    path: "{{ mongodb_replication_key_file }}"
  register: stat_repl_key_file

- name: replication | Generating Replication Set Keyfile
  shell: openssl rand -base64 756 | xargs echo -n
  register: repl_set_key
  when:
    - not stat_repl_key_file.stat.exists
    - "'master' in group_names"

- name: Mongo Replset | Creating Replication Set Keyfile {{ mongodb_replication_key_file }}
  file:
    path: "{{ mongodb_replication_key_file }}"
    state: touch
    mode: 0400
  when:
    - not stat_repl_key_file.stat.exists

- name: Mongo Replset | Adding Replication Set Key to {{ mongodb_replication_key_file }}
  lineinfile:
    dest: "{{ mongodb_replication_key_file }}"
    line: "{{ hostvars[groups['master'][0]]['repl_set_key']['stdout'] }}"
  when:
    - not stat_repl_key_file.stat.exists

- name: Mongo Replset | Set permission for {{ mongodb_replication_key_file }}
  file:
    path: "{{ mongodb_replication_key_file }}"
    owner: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
    group: "{{ 'mongodb' if ansible_os_family == 'Debian' else 'mongod' }}"
    mode: 0400
