---

- name: Mongo Config | Create config directories
  file:
    state: directory
    path: "{{ mongodb_conf_file | dirname }}"
    owner: root
    group: root
    mode: "0755"
  notify: mongodb restart


- name: Mongo Config | Configure MongoDB init-service and daemon
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: mongod-init.conf.j2
      dest: "{{ mongodb_conf_file }}"
    - src: mongod.service.j2
      dest: "{{ mongodb_daemon_unitfile }}"
  notify:
    - systemd reload
    - mongodb restart


- name: Mongo Config | Create database directory {{ mongodb_conf_db_dir }} 
  file:
    path: "{{ mongodb_conf_db_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod
  when: mongodb_conf_log_dir  != "/var/lib/mongo"


- name: Mongo Config | Create log directory {{ mongodb_conf_log_dir }} 
  file:
    path: "{{ mongodb_conf_log_dir }}"
    state: directory
    recurse: yes
    mode: '0755'
    owner: mongod
    group: mongod
  when: mongodb_conf_log_dir  != "/var/log/mongodb"


- name: Mongo Config | Disable Transparent Huge Pages (THP)
  template:
    src: disable-transparent-huge-pages.service.j2
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: "0644"
  notify: systemd reload

- name: Mongo Config | Start and enable disable-transparent-huge-pages service
  service:
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
  notify: mongodb restart