---

- name: Remove configfile created with package installation
  file:
    path: /etc/mongod.conf
    state: absent  
    
- name: Deploy auth configuration for MongoDB
  template:
    src: mongod.conf.j2
    dest: "{{ mongodb_conf_file }}"
    owner: root
    group: root    
    mode: "0644"
  notify:
    - mongodb restart  
