---
- name: Install RedHat | RPM GPG key MongoDB {{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }}
  rpm_key:
    state: present
    key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }}.asc"
  when: mongodb_enable_yum_repository

- name: Install RedHat | Create MongoDB {{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }} repository
  yum_repository:
    name: MongoDB-{{ mongodb_install_version_major }}-{{ mongodb_install_version_minor }}
    description: "MongoDB Repo"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }}/$basearch/"
    gpgcheck: true
    state: present
  when: mongodb_enable_yum_repository

- name: Install RedHat | Install MongoDB {{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }} packages
  yum:
    name:
      - mongodb-org-{{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }}.{{ mongodb_install_version_patch }}
      - mongodb-org-server-{{ mongodb_install_version_major }}.{{ mongodb_install_version_minor }}.{{ mongodb_install_version_patch }}
      - numactl
    state: present

- name: Install RedHat | Install YUM/DNF versionlock plugin
  yum:
    name: python3-dnf-plugin-versionlock
    state: present
  when: mongodb_install_package_lock

- name: Install RedHat | Checking versionlock for MongoDB packages
  shell: dnf versionlock list
  args:
    warn: false
  register: versionlock_result
  when: mongodb_install_package_lock

- name: Install RedHat | Enable versionlock for MongoDB packages
  shell: dnf versionlock add {{ item }}
  args:
    warn: false
  loop:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-mongos
    - mongodb-org-tools
  when:
    - mongodb_install_package_lock
    - not "mongodb" in versionlock_result.stdout
