---
# tasks file for mongodb-replicaset

- include: install.redhat.yml
  when: ansible_os_family == "RedHat"

- include: install.ubuntu.yml
  when: ansible_os_family == "Debian"

- include: config.hosts.yml

- include: config.directories.yml

- include: config.selinux.yml
  when: ansible_os_family == "RedHat"

- include: config.init_service.yml

- include: config.firewalld.yml

- include: config.systemd_units.yml

- include: config.pymongo.yml

- include: config.mongo_users.yml

- include: config.mongo_standalone_service.yml
  when: not mongodb_replication_enabled

- include: config.replication_keyfile.yml
  when: mongodb_replication_enabled

- include: config.mongo_reple_service.yml
  when: mongodb_replication_enabled

- include: config.replication.yml
  when: mongodb_replication_enabled