---
# tasks file for mongodb-replicaset

- include: install.redhat.yml
- include: configure.redhat.yml
- include: selinux.yml
  when: ansible_facts['os_family'] == "RedHat"
- include: common.accounts.yml
- include: final.redhat.yml
- include: configure.firewalld.yml