---

- name: SELinux | Disable service
  selinux:
    state: disabled
  when: not configure_selinux

- name: SELinux | Enable service
  selinux:
    state: enforcing
    policy: targeted
  when: configure_selinux

- name: SELinux | Install support packages
  yum:
    name:
      - checkpolicy
      - policycoreutils-python-utils
    state: present
  when: configure_selinux

- name: SELinux | mongodb_cgroup_memory | Copy custom policy
  copy: 
    src: selinux/mongodb_cgroup_memory.te
    dest: /tmp/mongodb_cgroup_memory.te
  when: configure_selinux

- name: SELinux | mongodb_cgroup_memory | Compile custom policy module
  command: checkmodule -M -m -o /tmp/mongodb_cgroup_memory.mod /tmp/mongodb_cgroup_memory.te
  when: configure_selinux

- name: SELinux | mongodb_cgroup_memory | Build custom policy package
  command: semodule_package -o /tmp/mongodb_cgroup_memory.pp -m /tmp/mongodb_cgroup_memory.mod
  when: configure_selinux

- name: SELinux | mongodb_cgroup_memory | Load custom policy package
  command: semodule -i /tmp/mongodb_cgroup_memory.pp
  when: configure_selinux

- name: SELinux | Set MongoDB context for {{ mongodb_conf_db_dir }} directory
  sefcontext:
    target: "{{ mongodb_conf_db_dir }}(/.*)?"
    setype: mongod_var_lib_t
    reload: true
    state: present
  when: 
    - configure_selinux
    - mongodb_conf_log_dir  != "/var/lib/mongo"
  notify: mongodb restart

- name: SELinux | Set MongoDB context for {{ mongodb_conf_log_dir }} directory
  sefcontext:
    target: "{{ mongodb_conf_log_dir }}(/.*)?"
    setype: mongod_log_t
    reload: true
    state: present
  when: 
    - configure_selinux
    - mongodb_conf_log_dir  != "/var/log/mongodb"
  notify: mongodb restart

- name: SELinux | Ensure MongoDB file contexts are applied
  shell: restorecon -vr "{{ item }}"
  with_items:
    - "{{ mongodb_conf_db_dir }}"
    - "{{ mongodb_conf_log_dir }}"
  register: restorecon
  changed_when: restorecon.stdout != ""

- name: SELinux | Configure MongoDB network port {{ mongodb_conf_port }}
  seport:
    ports: "{{ mongodb_conf_port }}"
    proto: tcp
    setype: mongod_port_t
    reload: true
    state: present
  notify: mongodb restart
  when: ansible_selinux and ansible_selinux.status == "enabled"
